package cc.theends6.sfx.internal.bootstrap;

import cc.theends6.sfx.api.item.SfxItemRegistry;
import org.bukkit.Material;

import static cc.theends6.sfx.internal.bootstrap.LegacySfBootstrapSupport.registerEnderTalismanVariant;
import static cc.theends6.sfx.internal.bootstrap.LegacySfBootstrapSupport.registerLegacyItem;

final class LegacySfItemBootstrapPart2 {
    private LegacySfItemBootstrapPart2() {
    }

    static void register(SfxItemRegistry registry) {
        registerLegacyItem(registry, "sf:hook", "sf:technical_components", Material.FLINT, "&bHook", null, null, new String[] {});
        registerLegacyItem(registry, "sf:sifted_ore", "sf:technical_components", Material.GUNPOWDER, "&6Sifted Ore", null, null, new String[] {});
        registerLegacyItem(registry, "sf:stone_chunk", "sf:technical_components", Material.PLAYER_HEAD, "&6Stone Chunk", "ce8f5adb14d6c9f6b810d027543f1a8c1f417e2fed993c97bcd89c74f5e2e8", null, new String[] {});
        registerLegacyItem(registry, "sf:lava_crystal", "sf:technical_components", Material.PLAYER_HEAD, "&4Lava Crystal", "a3ad8ee849edf04ed9a26ca3341f6033bd76dcc4231ed1ea63b7565751b27ac", null, new String[] {});
        registerLegacyItem(registry, "sf:salt", "sf:technical_components", Material.SUGAR, "&fSalt", null, null, new String[] {});
        registerLegacyItem(registry, "sf:cheese", "sf:technical_components", Material.PLAYER_HEAD, "&fCheese", "34febbc15d1d4cc62bedc5d7a2b6f0f46cd5b0696a884de75e289e35cbb53a0", null, new String[] {});
        registerLegacyItem(registry, "sf:butter", "sf:technical_components", Material.PLAYER_HEAD, "&fButter", "b66b19f7d635d03473891df33017c549363209a8f6328a8542c213d08525e", null, new String[] {});
        registerLegacyItem(registry, "sf:duct_tape", "sf:technical_components", Material.PLAYER_HEAD, "&8Duct Tape", "b2faaceab6384fff5ed24bb44a4af2f584eb1382729ecd93a5369acfd6654", null, new String[] {"", "&fYou can repair Items using this", "&fin an Auto-Anvil"});
        registerLegacyItem(registry, "sf:heavy_cream", "sf:technical_components", Material.SNOWBALL, "&fHeavy Cream", null, null, new String[] {});
        registerLegacyItem(registry, "sf:crushed_ore", "sf:technical_components", Material.GUNPOWDER, "&6Crushed Ore", null, null, new String[] {});
        registerLegacyItem(registry, "sf:pulverized_ore", "sf:technical_components", Material.GUNPOWDER, "&6Pulverized Ore", null, null, new String[] {});
        registerLegacyItem(registry, "sf:pure_ore_cluster", "sf:technical_components", Material.GUNPOWDER, "&6Pure Ore Cluster", null, null, new String[] {});
        registerLegacyItem(registry, "sf:small_uranium", "sf:technical_components", Material.PLAYER_HEAD, "&cSmall Chunk of Uranium", "c8b29afa6d6dc923e2e1324bf8192750f7bdbddc689632a2b6c18d9fe7a5e", null, new String[] {"", "&a鈽?7 Radiation level: &eMODERATE", "&8鈬?&4Hazmat Suit required!"});
        registerLegacyItem(registry, "sf:tiny_uranium", "sf:technical_components", Material.PLAYER_HEAD, "&cTiny Pile of Uranium", "c8b29afa6d6dc923e2e1324bf8192750f7bdbddc689632a2b6c18d9fe7a5e", null, new String[] {"", "&a鈽?7 Radiation level: &eLOW"});
        registerLegacyItem(registry, "sf:solar_panel", "sf:technical_components", Material.DAYLIGHT_DETECTOR, "&9Photovoltaic Cell", null, null, new String[] {"", "&7Important component for", "&7crafting a &bSolar Generator"});
        registerLegacyItem(registry, "sf:plastic_sheet", "sf:technical_components", Material.PAPER, "&fPlastic Sheet", null, null, new String[] {});
        registerLegacyItem(registry, "sf:magnet", "sf:technical_components", Material.PLAYER_HEAD, "&cMagnet", "aba8ebc4c6a81730947499bf7e1d5e73fed6c1bb2c051e96d35eb16d24610e7", null, new String[] {});
        registerLegacyItem(registry, "sf:necrotic_skull", "sf:technical_components", Material.PLAYER_HEAD, "&cNecrotic Skull", "7953b6c68448e7e6b6bf8fb273d7203acd8e1be19e81481ead51f45de59a8", null, new String[] {});
        registerLegacyItem(registry, "sf:essence_of_afterlife", "sf:technical_components", Material.GUNPOWDER, "&4Essence of Afterlife", null, null, new String[] {});
        registerLegacyItem(registry, "sf:strange_nether_goo", "sf:technical_components", Material.PURPLE_DYE, "&5Strange Nether Goo", null, null, new String[] {"", "&fA strange bio matter that", "&fcan be acquired from", "&fbartering with Piglins"});
        registerLegacyItem(registry, "sf:electro_magnet", "sf:technical_components", Material.PLAYER_HEAD, "&cElectromagnet", "aba8ebc4c6a81730947499bf7e1d5e73fed6c1bb2c051e96d35eb16d24610e7", null, new String[] {});
        registerLegacyItem(registry, "sf:heating_coil", "sf:technical_components", Material.PLAYER_HEAD, "&cHeating Coil", "7e3bc4893ba41a3f73ee28174cdf4fef6b145e41fe6c82cb7be8d8e9771a5", null, new String[] {});
        registerLegacyItem(registry, "sf:cooling_unit", "sf:technical_components", Material.PLAYER_HEAD, "&bCooling Unit", "754bad86c99df780c889a1098f77648ead7385cc1ddb093da5a7d8c4c2ae54d", null, new String[] {});
        registerLegacyItem(registry, "sf:electric_motor", "sf:technical_components", Material.PLAYER_HEAD, "&cElectric Motor", "8cbca012f67e54de9aee72ff424e056c2ae58de5eacc949ab2bcd9683cec", null, new String[] {});
        registerLegacyItem(registry, "sf:cargo_motor", "sf:cargo", Material.PLAYER_HEAD, "&3Cargo Motor", "8e47f99abcd645a3ef1122c9d850a981979f431ba293255c1680e91ab117ed35", null, new String[] {"", "&7Important ingredient for items", "&7related to Cargo Management"});
        registerLegacyItem(registry, "sf:scroll_of_dimensional_teleposition", "sf:technical_components", Material.PAPER, "&6Scroll of Dimensional Teleposition", null, null, new String[] {"", "&cThis Scroll is capable of creating", "&ca temporary black Hole which pulls", "&cnearby Entities into itself and sends", "&cthem into another Dimension where", "&ceverything is turned around", "", "&fIn other words: Makes Entities turn by 180 Degrees"});
        registerLegacyItem(registry, "sf:tome_of_knowledge_sharing", "sf:technical_components", Material.ENCHANTED_BOOK, "&6Tome of Knowledge Sharing", null, null, new String[] {"&7Owner: &bNone", "", "&eRight Click&7 to bind this Tome to yourself", "", "", "&eRight Click&7 to obtain all Researches by", "&7the previously assigned Owner"});
        registerLegacyItem(registry, "sf:hardened_glass", "sf:technical_components", Material.LIGHT_GRAY_STAINED_GLASS, "&7Hardened Glass", null, null, new String[] {"", "&fWithstands Explosions"});
        registerLegacyItem(registry, "sf:wither_proof_obsidian", "sf:technical_components", Material.OBSIDIAN, "&5Wither-Proof Obsidian", null, null, new String[] {"", "&fWithstands Explosions", "&fWithstands Wither Bosses"});
        registerLegacyItem(registry, "sf:wither_proof_glass", "sf:technical_components", Material.PURPLE_STAINED_GLASS, "&5Wither-Proof Glass", null, null, new String[] {"", "&fWithstands Explosions", "&fWithstands Wither Bosses"});
        registerLegacyItem(registry, "sf:reinforced_plate", "sf:technical_components", Material.PAPER, "&7Reinforced Plate", null, null, new String[] {});
        registerLegacyItem(registry, "sf:ancient_pedestal", "sf:technical_components", Material.DISPENSER, "&dAncient Pedestal", null, null, new String[] {"", "&5Part of the Ancient Altar"});
        registerLegacyItem(registry, "sf:ancient_altar", "sf:technical_components", Material.ENCHANTING_TABLE, "&dAncient Altar", null, null, new String[] {"", "&5Multi-Block Altar for", "&5magical Crafting Processes"});
        registerLegacyItem(registry, "sf:copper_wire", "sf:technical_components", Material.STRING, "&6Copper Wire", null, null, new String[] {"", "&6Crucial component in electric modules"});
        registerLegacyItem(registry, "sf:crafting_motor", "sf:technical_components", Material.PLAYER_HEAD, "&6Crafting Motor", "1003620899f1afa271e8e521ecbee2977a06c8529d3f389e8cc04af06d8c7940", null, new String[] {"", "&7Important component of Auto-Crafters"});
        registerLegacyItem(registry, "sf:rainbow_wool", "sf:rainbow_blocks", Material.WHITE_WOOL, "&5Rainbow Wool", null, null, new String[] {"", "&dCycles through all Colors of the Rainbow!"});
        registerLegacyItem(registry, "sf:rainbow_glass", "sf:rainbow_blocks", Material.WHITE_STAINED_GLASS, "&5Rainbow Glass", null, null, new String[] {"", "&dCycles through all Colors of the Rainbow!"});
        registerLegacyItem(registry, "sf:rainbow_clay", "sf:rainbow_blocks", Material.WHITE_TERRACOTTA, "&5Rainbow Clay", null, null, new String[] {"", "&dCycles through all Colors of the Rainbow!"});
        registerLegacyItem(registry, "sf:rainbow_glass_pane", "sf:rainbow_blocks", Material.WHITE_STAINED_GLASS_PANE, "&5Rainbow Glass Pane", null, null, new String[] {"", "&dCycles through all Colors of the Rainbow!"});
        registerLegacyItem(registry, "sf:rainbow_concrete", "sf:rainbow_blocks", Material.WHITE_CONCRETE, "&5Rainbow Concrete", null, null, new String[] {"", "&dCycles through all Colors of the Rainbow!"});
        registerLegacyItem(registry, "sf:rainbow_glazed_terracotta", "sf:rainbow_blocks", Material.WHITE_GLAZED_TERRACOTTA, "&5Rainbow Glazed Terracotta", null, null, new String[] {"", "&dCycles through all Colors of the Rainbow!"});
        registerLegacyItem(registry, "sf:rainbow_wool_xmas", "sf:seasonal", Material.WHITE_WOOL, "&5Rainbow Wool &7(Christmas)", null, null, new String[] {"", "&2[Christmas Edition]"});
        registerLegacyItem(registry, "sf:rainbow_glass_xmas", "sf:seasonal", Material.WHITE_STAINED_GLASS, "&5Rainbow Glass &7(Christmas)", null, null, new String[] {"", "&2[Christmas Edition]"});
        registerLegacyItem(registry, "sf:rainbow_clay_xmas", "sf:seasonal", Material.WHITE_TERRACOTTA, "&5Rainbow Clay &7(Christmas)", null, null, new String[] {"", "&2[Christmas Edition]"});
        registerLegacyItem(registry, "sf:rainbow_glass_pane_xmas", "sf:seasonal", Material.WHITE_STAINED_GLASS_PANE, "&5Rainbow Glass Pane &7(Christmas)", null, null, new String[] {"", "&2[Christmas Edition]"});
        registerLegacyItem(registry, "sf:rainbow_concrete_xmas", "sf:seasonal", Material.WHITE_CONCRETE, "&5Rainbow Concrete &7(Christmas)", null, null, new String[] {"", "&2[Christmas Edition]"});
        registerLegacyItem(registry, "sf:rainbow_glazed_terracotta_xmas", "sf:seasonal", Material.WHITE_GLAZED_TERRACOTTA, "&5Rainbow Glazed Terracotta &7(Christmas)", null, null, new String[] {"", "&2[Christmas Edition]"});
        registerLegacyItem(registry, "sf:rainbow_wool_valentine", "sf:seasonal", Material.PINK_WOOL, "&5Rainbow Wool &7(Valentine's Day)", null, null, new String[] {"", "&5[&dValentine's Day Edition&5]"});
        registerLegacyItem(registry, "sf:rainbow_glass_valentine", "sf:seasonal", Material.PINK_STAINED_GLASS, "&5Rainbow Glass &7(Valentine's Day)", null, null, new String[] {"", "&5[&dValentine's Day Edition&5]"});
        registerLegacyItem(registry, "sf:rainbow_clay_valentine", "sf:seasonal", Material.PINK_TERRACOTTA, "&5Rainbow Clay &7(Valentine's Day)", null, null, new String[] {"", "&5[&dValentine's Day Edition&5]"});
        registerLegacyItem(registry, "sf:rainbow_glass_pane_valentine", "sf:seasonal", Material.PINK_STAINED_GLASS_PANE, "&5Rainbow Glass Pane &7(Valentine's Day)", null, null, new String[] {"", "&5[&dValentine's Day Edition&5]"});
        registerLegacyItem(registry, "sf:rainbow_concrete_valentine", "sf:seasonal", Material.PINK_CONCRETE, "&5Rainbow Concrete &7(Valentine's Day)", null, null, new String[] {"", "&5[&dValentine's Day Edition&5]"});
        registerLegacyItem(registry, "sf:rainbow_glazed_terracotta_valentine", "sf:seasonal", Material.PINK_GLAZED_TERRACOTTA, "&5Rainbow Glazed Terracotta &7(Valentine's Day)", null, null, new String[] {"", "&5[&dValentine's Day Edition&5]"});
        registerLegacyItem(registry, "sf:rainbow_wool_halloween", "sf:seasonal", Material.ORANGE_WOOL, "&5Rainbow Wool &7(Halloween)", null, null, new String[] {"", "&c[&6Halloween Edition&c]"});
        registerLegacyItem(registry, "sf:rainbow_glass_halloween", "sf:seasonal", Material.ORANGE_STAINED_GLASS, "&5Rainbow Glass &7(Halloween)", null, null, new String[] {"", "&c[&6Halloween Edition&c]"});
        registerLegacyItem(registry, "sf:rainbow_clay_halloween", "sf:seasonal", Material.ORANGE_TERRACOTTA, "&5Rainbow Clay &7(Halloween)", null, null, new String[] {"", "&c[&6Halloween Edition&c]"});
        registerLegacyItem(registry, "sf:rainbow_glass_pane_halloween", "sf:seasonal", Material.ORANGE_STAINED_GLASS_PANE, "&5Rainbow Glass Pane &7(Halloween)", null, null, new String[] {"", "&c[&6Halloween Edition&c]"});
        registerLegacyItem(registry, "sf:rainbow_concrete_halloween", "sf:seasonal", Material.ORANGE_CONCRETE, "&5Rainbow Concrete &7(Halloween)", null, null, new String[] {"", "&c[&6Halloween Edition&c]"});
        registerLegacyItem(registry, "sf:rainbow_glazed_terracotta_halloween", "sf:seasonal", Material.ORANGE_GLAZED_TERRACOTTA, "&5Rainbow Glazed Terracotta &7(Halloween)", null, null, new String[] {"", "&c[&6Halloween Edition&c]"});
        registerLegacyItem(registry, "sf:copper_ingot", "sf:ingots", Material.BRICK, "&bCopper Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:tin_ingot", "sf:ingots", Material.IRON_INGOT, "&bTin Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:silver_ingot", "sf:ingots", Material.IRON_INGOT, "&bSilver Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:aluminum_ingot", "sf:ingots", Material.IRON_INGOT, "&bAluminum Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:lead_ingot", "sf:ingots", Material.IRON_INGOT, "&bLead Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:zinc_ingot", "sf:ingots", Material.IRON_INGOT, "&bZinc Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:magnesium_ingot", "sf:ingots", Material.IRON_INGOT, "&bMagnesium Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:steel_ingot", "sf:alloy_carbon_iron", Material.IRON_INGOT, "&bSteel Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:bronze_ingot", "sf:alloy_copper_tin", Material.BRICK, "&bBronze Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:duralumin_ingot", "sf:alloy_copper_aluminum", Material.IRON_INGOT, "&bDuralumin Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:billon_ingot", "sf:alloy_copper_silver", Material.IRON_INGOT, "&bBillon Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:brass_ingot", "sf:alloy_copper_zinc", Material.GOLD_INGOT, "&bBrass Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:aluminum_brass_ingot", "sf:alloy_aluminum_brass", Material.GOLD_INGOT, "&bAluminum Brass Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:aluminum_bronze_ingot", "sf:alloy_aluminum_bronze", Material.GOLD_INGOT, "&bAluminum Bronze Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:corinthian_bronze_ingot", "sf:alloy_gold_silver_copper", Material.GOLD_INGOT, "&bCorinthian Bronze Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:solder_ingot", "sf:alloy_lead_tin", Material.IRON_INGOT, "&bSolder Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:damascus_steel_ingot", "sf:alloy_steel_iron_carbon", Material.IRON_INGOT, "&bDamascus Steel Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:hardened_metal_ingot", "sf:alloy_damascus_steel_duralumin_compressed_carbon_aluminium_bronze", Material.IRON_INGOT, "&b&lHardened Metal", null, null, new String[] {});
        registerLegacyItem(registry, "sf:reinforced_alloy_ingot", "sf:alloy_hardened_metal_corinthian_bronze_solder_billon_damascus_steel", Material.IRON_INGOT, "&b&lReinforced Alloy Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:ferrosilicon", "sf:alloy_iron_silicon", Material.IRON_INGOT, "&bFerrosilicon", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gilded_iron", "sf:alloy_iron_gold", Material.GOLD_INGOT, "&6&lGilded Iron", null, null, new String[] {});
        registerLegacyItem(registry, "sf:redstone_alloy", "sf:alloy_redstone_ferrosilicon", Material.BRICK, "&cRedstone Alloy Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:nickel_ingot", "sf:alloy_iron_copper", Material.IRON_INGOT, "&bNickel Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:cobalt_ingot", "sf:alloy_nickel_iron_copper", Material.IRON_INGOT, "&9Cobalt Ingot", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_4k", "sf:gold", Material.GOLD_INGOT, "&fGold Ingot &7(4-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_6k", "sf:gold", Material.GOLD_INGOT, "&fGold Ingot &7(6-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_8k", "sf:gold", Material.GOLD_INGOT, "&fGold Ingot &7(8-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_10k", "sf:gold", Material.GOLD_INGOT, "&fGold Ingot &7(10-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_12k", "sf:gold", Material.GOLD_INGOT, "&fGold Ingot &7(12-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_14k", "sf:gold", Material.GOLD_INGOT, "&fGold Ingot &7(14-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_16k", "sf:gold", Material.GOLD_INGOT, "&fGold Ingot &7(16-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_18k", "sf:gold", Material.GOLD_INGOT, "&fGold Ingot &7(18-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_20k", "sf:gold", Material.GOLD_INGOT, "&fGold Ingot &7(20-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_22k", "sf:gold", Material.GOLD_INGOT, "&fGold Ingot &7(22-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_24k", "sf:gold", Material.GOLD_INGOT, "&fGold Ingot &7(24-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:iron_dust", "sf:dusts", Material.GUNPOWDER, "&6Iron Dust", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_dust", "sf:dusts", Material.GLOWSTONE_DUST, "&6Gold Dust", null, null, new String[] {});
        registerLegacyItem(registry, "sf:tin_dust", "sf:dusts", Material.SUGAR, "&6Tin Dust", null, null, new String[] {});
        registerLegacyItem(registry, "sf:copper_dust", "sf:dusts", Material.GLOWSTONE_DUST, "&6Copper Dust", null, null, new String[] {});
        registerLegacyItem(registry, "sf:silver_dust", "sf:dusts", Material.SUGAR, "&6Silver Dust", null, null, new String[] {});
        registerLegacyItem(registry, "sf:aluminum_dust", "sf:dusts", Material.SUGAR, "&6Aluminum Dust", null, null, new String[] {});
        registerLegacyItem(registry, "sf:lead_dust", "sf:dusts", Material.GUNPOWDER, "&6Lead Dust", null, null, new String[] {});
        registerLegacyItem(registry, "sf:zinc_dust", "sf:dusts", Material.SUGAR, "&6Zinc Dust", null, null, new String[] {});
        registerLegacyItem(registry, "sf:magnesium_dust", "sf:dusts", Material.SUGAR, "&6Magnesium", null, null, new String[] {});
        registerLegacyItem(registry, "sf:sulfate", "sf:dusts", Material.GLOWSTONE_DUST, "&6Sulfate", null, null, new String[] {});
        registerLegacyItem(registry, "sf:silicon", "sf:dusts", Material.FIREWORK_STAR, "&6Silicon", null, null, new String[] {});
        registerLegacyItem(registry, "sf:gold_24k_block", "sf:dusts", Material.GOLD_BLOCK, "&fGold Block &7(24-Carat)", null, null, new String[] {});
        registerLegacyItem(registry, "sf:synthetic_diamond", "sf:gems", Material.DIAMOND, "&bSynthetic Diamond", null, null, new String[] {"", "&fThis item can be used in a", "&fworkbench and acts like a normal Diamond"});
        registerLegacyItem(registry, "sf:synthetic_emerald", "sf:gems", Material.EMERALD, "&bSynthetic Emerald", null, null, new String[] {"", "&fThis item can be used to", "&ftrade with Villagers"});
        registerLegacyItem(registry, "sf:synthetic_sapphire", "sf:gems", Material.PLAYER_HEAD, "&bSynthetic Sapphire", "e35032f4d7d01de8ec99d89f8723012d4e74fa73022c4facf1b57c7ff6ff0", null, new String[] {"", "&fThis item can be used in a", "&fworkbench and acts like Lapis Lazuli"});
        registerLegacyItem(registry, "sf:carbonado", "sf:gems", Material.PLAYER_HEAD, "&b&lCarbonado", "12f4b1577f5160c6893172571c4a71d8b321cdceaa032c6e0e3b60e0b328fa", null, new String[] {"", "&7&o\"Black Diamond\""});
        registerLegacyItem(registry, "sf:raw_carbonado", "sf:gems", Material.PLAYER_HEAD, "&bRaw Carbonado", "eb49e6ec10771e899225aea73cd8cf03684f411d1415c7323c93cb9476230", null, new String[] {});
        registerLegacyItem(registry, "sf:uranium", "sf:gems", Material.PLAYER_HEAD, "&4Uranium", "c8b29afa6d6dc923e2e1324bf8192750f7bdbddc689632a2b6c18d9fe7a5e", null, new String[] {"", "&a鈽?7 Radiation level: &6HIGH", "&8鈬?&4Hazmat Suit required!"});
        registerLegacyItem(registry, "sf:neptunium", "sf:gems", Material.PLAYER_HEAD, "&aNeptunium", "4edea6bfd37e49de43f154fe6fca617d4129e61b95759a3d49a15935a1c2dcf0", null, new String[] {"", "&a鈽?7 Radiation level: &6HIGH", "&8鈬?&4Hazmat Suit required!"});
        registerLegacyItem(registry, "sf:plutonium", "sf:gems", Material.PLAYER_HEAD, "&7Plutonium", "25cf91b7388665a6d7c1b6026bdb2322c6d278997a44478677cbcc15f76124f", null, new String[] {"", "&a鈽?7 Radiation level: &cVERY HIGH", "&8鈬?&4Hazmat Suit required!"});
        registerLegacyItem(registry, "sf:boosted_uranium", "sf:gems", Material.PLAYER_HEAD, "&2Boosted Uranium", "6837ca12f222f4787196a17b8ab656985f8404c50767adbcb6e7f14254fee", null, new String[] {"", "&a鈽?7 Radiation level: &cVERY HIGH", "&8鈬?&4Hazmat Suit required!"});
        registerLegacyItem(registry, "sf:common_talisman", "sf:talisman", Material.EMERALD, "&6Common Talisman", null, null, new String[] {});
        registerLegacyItem(registry, "sf:ender_talisman", "sf:talisman", Material.EMERALD, "&5Ender Talisman", null, null, new String[] {});
        registerLegacyItem(registry, "sf:anvil_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Anvil", null, null, new String[] {"", "&fEach Talisman can prevent", "&f1 Tool from breaking, but will then", "&fbe consumed", "", "&4&lWARNING:", "&4This Talisman does not work on", "&4Tools which are too powerful", "&4due to their complexity"});
        registerLegacyItem(registry, "sf:miner_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Miner", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it has", "&fa 20% chance of doubling", "&fall Ores you mine"});
        registerLegacyItem(registry, "sf:farmer_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Farmer", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it has", "&fa 20% chance of doubling", "&fall crops you harvest"});
        registerLegacyItem(registry, "sf:hunter_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Hunter", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it has", "&fa 20% chance of doubling", "&fall Drops from Mobs you kill"});
        registerLegacyItem(registry, "sf:lava_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Lava Walker", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it will", "&fgive you Fire Resistance", "&fas soon as you touch Lava", "&fbut will then be consumed"});
        registerLegacyItem(registry, "sf:water_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Water Breather", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it will", "&fgive you the ability", "&fto breath underwater as", "&fsoon as you start drowning", "&fbut will then be consumed"});
        registerLegacyItem(registry, "sf:angel_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Angel", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it has a", "&f75% chance to prevent you", "&ffrom taking Fall Damage"});
        registerLegacyItem(registry, "sf:fire_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Firefighter", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it will", "&fgive you Fire Resistance", "&fas soon as you start burning", "&fbut will then be consumed"});
        registerLegacyItem(registry, "sf:magician_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Magician", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it gives", "&fyou a 80% Luck Bonus on Enchanting", "&fYou will sometimes get an Extra Enchantment"});
        registerLegacyItem(registry, "sf:traveller_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Traveller", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it gives", "&fyou a 60% Chance for a decent", "&fSpeed Buff when you start sprinting"});
        registerLegacyItem(registry, "sf:warrior_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Warrior", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it gives", "&fyou Strength III whenever you get hit", "&fbut will then be consumed"});
        registerLegacyItem(registry, "sf:knight_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Knight", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it gives", "&fyou a 30% Chance for 5 Seconds of Regeneration", "&fwhenever You get hit", "&fbut will then be consumed"});
        registerLegacyItem(registry, "sf:whirlwind_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Whirlwind", null, null, new String[] {"", "&fHaving this Talisman", "&fin your Inventory will reflect", "&f60% of any projectiles fired at you.", "&e&oOnly a thrown Trident can pierce", "&e&othrough this layer of protection"});
        registerLegacyItem(registry, "sf:wizard_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Wizard", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your Inventory it allows you to", "&fobtain Fortune Level 4/5 however", "&fit also has a chance to lower the", "&fLevel of some Enchantments on your Item"});
        registerLegacyItem(registry, "sf:caveman_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Caveman", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your inventory it gives", "&fyou a 50% chance for a decent", "&fHaste buff when you mine any ore"});
        registerLegacyItem(registry, "sf:wise_talisman", "sf:talisman", Material.EMERALD, "&aTalisman of the Wise", null, null, new String[] {"", "&fWhile you have this Talisman", "&fin your inventory it gives", "&fyou a 20% chance of doubling", "&fany experience you obtain"});
        registerEnderTalismanVariant(registry, "anvil_talisman", "&aTalisman of the Anvil");
        registerEnderTalismanVariant(registry, "miner_talisman", "&aTalisman of the Miner");
        registerEnderTalismanVariant(registry, "farmer_talisman", "&aTalisman of the Farmer");
        registerEnderTalismanVariant(registry, "hunter_talisman", "&aTalisman of the Hunter");
        registerEnderTalismanVariant(registry, "lava_talisman", "&aTalisman of the Lava Walker");
        registerEnderTalismanVariant(registry, "water_talisman", "&aTalisman of the Water Breather");
        registerEnderTalismanVariant(registry, "angel_talisman", "&aTalisman of the Angel");
        registerEnderTalismanVariant(registry, "fire_talisman", "&aTalisman of the Firefighter");
        registerEnderTalismanVariant(registry, "magician_talisman", "&aTalisman of the Magician");
        registerEnderTalismanVariant(registry, "traveller_talisman", "&aTalisman of the Traveller");
        registerEnderTalismanVariant(registry, "warrior_talisman", "&aTalisman of the Warrior");
        registerEnderTalismanVariant(registry, "knight_talisman", "&aTalisman of the Knight");
        registerEnderTalismanVariant(registry, "whirlwind_talisman", "&aTalisman of the Whirlwind");
        registerEnderTalismanVariant(registry, "wizard_talisman", "&aTalisman of the Wizard");
        registerEnderTalismanVariant(registry, "caveman_talisman", "&aTalisman of the Caveman");
        registerEnderTalismanVariant(registry, "wise_talisman", "&aTalisman of the Wise");
        registerLegacyItem(registry, "sf:staff_elemental", "sf:staves", Material.STICK, "&6Elemental Staff", null, null, new String[] {});
        registerLegacyItem(registry, "sf:staff_elemental_wind", "sf:staves", Material.STICK, "&6Elemental Staff &7- &b&oWind", null, null, new String[] {"", "&7Element: &b&oWind", "", "&eRight Click&7 to launch yourself forward"});
        registerLegacyItem(registry, "sf:staff_elemental_fire", "sf:staves", Material.STICK, "&6Elemental Staff &7- &c&oFire", null, null, new String[] {"", "&7Element: &c&oFire"});
        registerLegacyItem(registry, "sf:staff_elemental_water", "sf:staves", Material.STICK, "&6Elemental Staff &7- &1&oWater", null, null, new String[] {"", "&7Element: &1&oWater", "", "&eRight Click&7 to extinguish yourself"});
        registerLegacyItem(registry, "sf:staff_elemental_storm", "sf:staves", Material.STICK, "&6Elemental Staff &7- &8&oStorm", null, null, new String[] {"", "&7Element: &8&oStorm", "", "&eRight Click&7 to summon a lightning", "&e8 Uses &7left"});
        registerLegacyItem(registry, "sf:enhanced_crafting_table", "sf:multiblocks", Material.CRAFTING_TABLE, "&eEnhanced Crafting Table", null, null, new String[] {"", "&aA regular Crafting Table cannot", "&ahold this massive Amount of Power..."});
        registerLegacyItem(registry, "sf:grind_stone", "sf:multiblocks", Material.DISPENSER, "&bGrind Stone", null, null, new String[] {"", "&aGrinds items down into other items"});
        registerLegacyItem(registry, "sf:armor_forge", "sf:multiblocks", Material.ANVIL, "&6Armor Forge", null, null, new String[] {"", "&aGives you the ability to create powerful armor"});
        registerLegacyItem(registry, "sf:makeshift_smeltery", "sf:multiblocks", Material.BLAST_FURNACE, "&eMakeshift Smeltery", null, null, new String[] {"", "&fImprovised version of the Smeltery", "&fthat only allows you to", "&fsmelt dusts into ingots"});
        registerLegacyItem(registry, "sf:smeltery", "sf:multiblocks", Material.FURNACE, "&6Smeltery", null, null, new String[] {"", "&fA high-temperature furnace", "&fthat allows you to smelt dusts", "&finto ingots and create alloys."});
        registerLegacyItem(registry, "sf:ore_crusher", "sf:multiblocks", Material.DISPENSER, "&bOre Crusher", null, null, new String[] {"", "&aCrushes ores to double them"});
        registerLegacyItem(registry, "sf:compressor", "sf:multiblocks", Material.PISTON, "&bCompressor", null, null, new String[] {"", "&aCompresses Items"});
        registerLegacyItem(registry, "sf:pressure_chamber", "sf:multiblocks", Material.GLASS, "&bPressure Chamber", null, null, new String[] {"", "&aCompresses Items even further"});
        registerLegacyItem(registry, "sf:magic_workbench", "sf:multiblocks", Material.CRAFTING_TABLE, "&6Magic Workbench", null, null, new String[] {"", "&dInfuses Items with magical Energy"});
        registerLegacyItem(registry, "sf:ore_washer", "sf:multiblocks", Material.CAULDRON, "&6Ore Washer", null, null, new String[] {"", "&aWashes Sifted Ore to filter Ores", "&aand gives you small Stone Chunks"});
        registerLegacyItem(registry, "sf:table_saw", "sf:multiblocks", Material.STONECUTTER, "&6Table Saw", null, null, new String[] {"", "&aAllows you to get 8 planks from 1 Log", "&a(Works with all log types)"});
        registerLegacyItem(registry, "sf:juicer", "sf:multiblocks", Material.GLASS_BOTTLE, "&aJuicer", null, null, new String[] {"", "&aAllows you to create delicious Juice"});
        registerLegacyItem(registry, "sf:automated_panning_machine", "sf:multiblocks", Material.BOWL, "&eAutomated Panning Machine", null, null, new String[] {"", "&fA MultiBlock Version of the Gold Pan", "&fand Nether Gold Pan combined in one machine."});
        registerLegacyItem(registry, "sf:industrial_miner", "sf:multiblocks", Material.GOLDEN_PICKAXE, "&bIndustrial Miner", null, null, new String[] {"", "&fThis Multiblock will mine any Ores", "&fin a 7x7 area underneath it.", "&fPlace coal or similar in its chest", "&fto fuel this machine."});
        registerLegacyItem(registry, "sf:advanced_industrial_miner", "sf:multiblocks", Material.DIAMOND_PICKAXE, "&cAdvanced Industrial Miner", null, null, new String[] {"", "&fThis Multiblock will mine any Ores", "&fin a 11x11 area underneath it.", "&fPlace a bucket of fuel or lava in", "&fits chest to fuel this machine.", "", "&a+ Silk Touch"});
        registerLegacyItem(registry, "sf:composter", "sf:machines", Material.CAULDRON, "&aComposter", null, null, new String[] {"", "&a&oCan convert various Materials over Time..."});
        registerLegacyItem(registry, "sf:crucible", "sf:machines", Material.CAULDRON, "&cCrucible", null, null, new String[] {"", "&a&oUsed to smelt Items into Liquids"});
        registerLegacyItem(registry, "sf:output_chest", "sf:machines", Material.CHEST, "&4Output Chest", null, null, new String[] {"", "&c&oA basic machine will try to put", "&c&oitems in this chest if it's placed", "&c&oadjacent to the dispenser."});
        registerLegacyItem(registry, "sf:ignition_chamber", "sf:machines", Material.DROPPER, "&4Automatic Ignition Chamber", null, null, new String[] {"", "&fPrevents the Smeltery from using up fire.", "&fJust fill it up with \"Flint and Steel\"", "&fand place it adjacent to the Smeltery's dispenser"});
        registerLegacyItem(registry, "sf:hologram_projector", "sf:machines", Material.QUARTZ_SLAB, "&bHologram Projector", null, null, new String[] {"", "&fProjects an Editable Hologram"});
        registerLegacyItem(registry, "sf:block_placer", "sf:machines", Material.DISPENSER, "&aBlock Placer", null, null, new String[] {"", "&fAll Blocks in this Dispenser", "&fwill automatically get placed"});
        registerLegacyItem(registry, "sf:enhanced_furnace", "sf:enhanced_furnaces", Material.FURNACE, "&7Enhanced Furnace - &eI", null, null, new String[] {"", "&7Processing Speed: &e1x", "&7Fuel Efficiency: &e1x", "&7Luck Multiplier: &e1x"});
        registerLegacyItem(registry, "sf:enhanced_furnace_2", "sf:enhanced_furnaces", Material.FURNACE, "&7Enhanced Furnace - &eII", null, null, new String[] {"", "&7Processing Speed: &e2x", "&7Fuel Efficiency: &e1x", "&7Luck Multiplier: &e1x"});
        registerLegacyItem(registry, "sf:enhanced_furnace_3", "sf:enhanced_furnaces", Material.FURNACE, "&7Enhanced Furnace - &eIII", null, null, new String[] {"", "&7Processing Speed: &e2x", "&7Fuel Efficiency: &e2x", "&7Luck Multiplier: &e1x"});
        registerLegacyItem(registry, "sf:enhanced_furnace_4", "sf:enhanced_furnaces", Material.FURNACE, "&7Enhanced Furnace - &eIV", null, null, new String[] {"", "&7Processing Speed: &e3x", "&7Fuel Efficiency: &e2x", "&7Luck Multiplier: &e1x"});
        registerLegacyItem(registry, "sf:enhanced_furnace_5", "sf:enhanced_furnaces", Material.FURNACE, "&7Enhanced Furnace - &eV", null, null, new String[] {"", "&7Processing Speed: &e3x", "&7Fuel Efficiency: &e2x", "&7Luck Multiplier: &e2x"});
    }
}
